services:
  core-keeper:
    image: escaping/core-keeper-dedicated:latest
    container_name: core-keeper-dedicated
    restart: unless-stopped
    stop_grace_period: 2m
    # Port is only needed if using direct connection mode
    # ports:
    #   - "$SERVER_PORT:$SERVER_PORT/udp"
    volumes:
      - core-keeper-data:/home/steam/core-keeper-dedicated
      - /mnt/nas/game-saves/core-keeper:/home/steam/core-keeper-data
    environment:
      - PASSWORD=${PASSWORD:?err}
      - WORLD_NAME=${WORLD_NAME:?err}
      - ACTIVATE_ALL_CONTENT=true
      
volumes:
  core-keeper-data: