services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "8500:5000"
    volumes:
      - /mnt/app_config/registry/data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: webhook-router
          url: http://webhook-router:3000/webhook
          timeout: 5s
          backoff: 1s

  webhook-router:
    image: ghcr.io/kyeotic/stook:latest
    container_name: webhook-router
    restart: unless-stopped
    extra_hosts:                                                       
        - "host.docker.internal:host-gateway"    
    environment:
      PORTAINER_URL: "https://host.docker.internal:9443"
      PORTAINER_API_KEY: "${PORTAINER_API_KEY}"
      LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
