---
# Create Samba LXC container

- name: create and configure Samba LXC
  ansible.builtin.include_role:
    name: lxc-create
  vars:
    lxc_vmid: "{{ samba_lxc_vmid }}"
    lxc_hostname: "{{ samba_lxc_hostname }}"
    lxc_cores: "{{ samba_lxc_cores }}"
    lxc_memory: "{{ samba_lxc_memory }}"
    lxc_swap: "{{ samba_lxc_swap }}"
    lxc_disk: "{{ samba_lxc_disk }}"
    lxc_storage: "{{ samba_lxc_storage }}"
    lxc_bridge: "{{ samba_lxc_bridge }}"
    lxc_ip: "{{ samba_lxc_ip }}"
    lxc_gateway: "{{ samba_lxc_gateway }}"
    lxc_template_name: "{{ samba_lxc_template_name }}"
    lxc_template: "{{ samba_lxc_template }}"
    lxc_onboot: "{{ samba_lxc_onboot }}"
    lxc_unprivileged: "{{ samba_lxc_unprivileged }}"
    lxc_features: "{{ samba_lxc_features }}"
    lxc_mounts: "{{ samba_lxc_mounts }}"

- name: finish SSH setup for Samba LXC
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/../lxc-create/tasks/ssh-setup.yml"
  vars:
    lxc_ip: "{{ samba_lxc_ip }}"
