version: "1"

default:
  repository: "rest:https://sd9j6dod:X23NkZv6sobxuAND@sd9j6dod.repo.borgbase.com"
  password-file: "~/restic-password"

  lock-timeout: "30m"

  backup:
    verbose: true
    source:
      - "/tank/container-backups/dump"
      - "/tank/nas"
      - "/tank/apps"
      - "/tank/media_root/media/music"
    exclude:
      - "/tank/apps/**/Plex Media Server/Cache/**"
      - "/tank/apps/**/Plex Media Server/Codecs/**"
      - "/tank/apps/**/Plex Media Server/Logs/**"

  schedules:
    daily:
      schedule: "daily, 04:00"
      run-before:
        # Don't run daily backup on Mondays (handled by weekly backup)
        # This avoid a double backup on Mondays
        - '[ "$(date +%u)" -ne 1 ] || echo "Skipping daily backup on Monday"'
        - '[ "$(date +%u)" -ne 1 ] || exit 0'
      backup:
        tag:
          - "daily"
      retention:
        keep-last: 1
        prune: false
        tag: ["daily"]

    weekly:
      schedule: "Mon, 04:00"
      backup:
        tag:
          - "weekly"
      retention:
        keep-last: 2
        prune: true
        tag: ["weekly"]
