version: "1"

default:
  repository: "rest:https://sd9j6dod:X23NkZv6sobxuAND@sd9j6dod.repo.borgbase.com"
  password-file: "~/restic-password"

  backup:
    verbose: true
    source:
      - "/tank/container-backups/dump"
      - "/tank/nas"
      - "/tank/apps"
      - "/tank/media_root/media/music"
    schedule: "Mon, 04:00"
  retention:
    group-by: ""
    before-backup: false
    after-backup: true
    keep-last: 3
    prune: true
    tag: true
    host: true

# To restore a backup, use a command like:
# resticprofile restore latest:/var/lib/vz/dump --target="/tank/container-backups/dump"
