#!/usr/bin/env bash

# Push the Caddyfile over SSH and reload the docker config

# make the Caddyfile and reload file relative to this script
SCRIPT_DIR="$(dirname "$0")"
scp "$SCRIPT_DIR/Caddyfile" root@192.168.0.13:/root/caddy/Caddyfile
scp "$SCRIPT_DIR/reload" root@192.168.0.13:/root/caddy/reload
ssh root@192.168.0.13 "(cd /root/caddy && ./reload)"