---
# NAS user/group for shared access (used by zfs-pool, lxc-users, samba)
nas_user: nas
nas_uid: 101000
nas_group: nas_shares
nas_gid: 110000

samba_lxc_vmid: 102
samba_lxc_hostname: kye-nas
samba_user: tkye
samba_user_uid: 1000
samba_group_name: nas_shares
samba_group_gid: 10000
samba_lxc_ip: "192.168.0.11/24"
# Bitwarden Secrets Manager secret ID containing the samba password
samba_bws_secret_id: "c65a3ce8-9145-4c17-9481-b3e1005e9adc"
# Bitwarden Secrets Manager secret ID containing the Portainer API key
portainer_bws_secret_id: "3627973b-9a14-44f5-9a5a-b3e3006cc4ae"

# Samba share definitions
samba_shares:
  - name: nas
    path: /mnt/nas
    comment: "NAS Share"
    read_only: false
    browseable: true
  - name: media
    path: /mnt/media_root
    comment: "Media Share"
    read_only: false
    browseable: true
  - name: apps
    path: /mnt/apps
    comment: "App Config Share"
    read_only: false
    browseable: true


# Mount points: host -> container mappings
samba_lxc_mounts:
  - { host: "/tank/nas", container: "/mnt/nas" }
  - { host: "/tank/apps", container: "/mnt/apps" }
  - { host: "/tank/media_root", container: "/mnt/media_root" }