---
# Proxmox directory storage for container backups

- name: check if container-backups storage exists
  command: pvesm status --storage container-backups
  register: storage_check
  failed_when: false
  changed_when: false

- name: create proxmox directory storage for container backups
  command:
    cmd: pvesm add dir container-backups --path /tank/container-backups --content backup
  when: storage_check.rc != 0
