services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /mnt/caddy:/data/caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '3'

