services:
  caddy:
    # build: . # no longer using custom version
    image: ghcr.io/williamjacksn/caddy-route53:2.10.2-1.6.0
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      # Uses aws ddns role with homelab user
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}
    logging:
      driver: 'json-file'
      options:
        max-size: '2m'
        max-file: '3'

volumes:
  caddy_data:
  caddy_config:
