services:
  caddy:
    build: .
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      # Uses aws ddns role with homelab user
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_ACCESS_SECRET=${AWS_ACCESS_SECRET}

volumes:
  caddy_data:
  caddy_config:
