all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

proxmox:
  hosts:
    homelab:
      ansible_host: 192.168.0.10
      ansible_user: root

caddy:
  hosts:
    caddy-container:
      ansible_host: 192.168.0.13
      ansible_user: root

docker:
  hosts:
    docker:
      ansible_host: 192.168.0.20
      ansible_user: root
