---
- name: Configure Proxmox
  hosts: proxmox
  gather_facts: false
  roles:
    - { role: pve-post-install, tags: [setup-proxmox] }
    - { role: proxmox-packages, tags: [setup-proxmox] }
    - { role: zfs-pool, tags: [setup-proxmox, restore-containers] }
    - role: restic
    - { role: proxmox-storage, tags: [setup-proxmox, restore-containers] }
    - { role: lxc-users, tags: [setup-proxmox] }
    - { role: gpu-access, tags: [setup-proxmox] }
    - { role: zed-discord, tags: [setup-proxmox] }
    - { role: container-restore, tags: [restore-containers] }
    - { role: docker-lxc, tags: [setup-docker] }
    - { role: samba-lxc, tags: [setup-samba] }
    - { role: caddy-lxc, tags: [setup-caddy] }
    - { role: adguard-lxc, tags: [setup-adguard] }
    - { role: tailscale-lxc, tags: [setup-tailscale] }
    - role: container-ssh

- name: Configure Caddy
  hosts: caddy
  gather_facts: false
  roles:
    - { role: caddy, tags: [setup-caddy] }

- name: Configure Docker
  hosts: docker
  gather_facts: false
  roles:
    - { role: docker-portainer, tags: [setup-docker] }
    - { role: portainer-stacks, tags: [setup-docker, docker-stacks] }
    - { role: docker-cleanup, tags: [setup-docker] }

- name: Configure Samba
  hosts: samba
  gather_facts: false
  roles:
    - { role: samba-config, tags: [setup-samba, sync-samba] }

- name: Configure Proxmox Backups
  hosts: proxmox
  gather_facts: false
  roles:
    - { role: proxmox-backup, tags: [setup-proxmox, setup-backup] }
