- name: Configure
  hosts: proxmox
  tasks:
    - name: sync restic profile
      synchronize:
        src: ../restic/restic.yaml
        dest: /root/profiles.yaml
  #  - name: Ping my hosts
  #    ansible.builtin.ping:

  #  - name: Print message
  #    ansible.builtin.debug:
  #     msg: Hello world