services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.10.2
    container_name: mealie
    restart: always
    ports:
      - "3100:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/mealie:/app/data
    environment:
      ALLOW_SIGNUP: "false"
      PUID: ${PUID:?err}
      PGID: ${PGID:?err}
      TZ: ${TIMEZONE:?err}
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://cook.kye.dev
      # SMTP
      SMTP_FROM_EMAIL: mealie.admin@kye.dev
      SMTP_HOST: smtp.mailbox.org
      SMTP_USER: tim@kye.dev
      SMTP_PASSWORD: ${SMTP_PASSWORD:?err}
      # OIDC / Auth0
      OIDC_AUTH_ENABLED: "true"
      OIDC_CONFIGURATION_URL: ${OIDC_CONFIGURATION_URL:?err}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:?err}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET:?err}
      OIDC_SIGNUP_ENABLED: "true"
      OIDC_PROVIDER_NAME: "Auth0"
      OIDC_USER_CLAIM: "email"
      OIDC_REMEMBER_ME: "true"

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: mealie-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN:?err}
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "3"
