#cloud-config
# ref: https://github.com/rancher/k3os/blob/master/README.md#configuration-reference
hostname: k3n$$NODE_NAME
ssh_authorized_keys:
- github:kyeotic
write_files:
- path: /var/lib/connman/default.configz
  # IPv4=<node_ip>/<subnet_mask>/<gateway_ip>
  content: |-
    [service_eth0]
    Type=ethernet
    IPv4=192.168.0.$$NODE_IP/255.255.255.0/192.168.0.1
    IPv6=off
    Nameservers=192.168.0.1

    TimeServers=0.pool.ntp.org,1.pool.ntp.org

    # SearchDomains=local
    # Domain=local

k3os:
  enabled: true
  password: beeline
  # k3s_args:
  # - server
  # - "--cluster-init"
