services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/app_config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    ports:
      - 8123:8123
  code-server:
    container_name: homeassistant-code-server
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
      - PASSWORD=${CODE_SERVER_PASSWORD:?err}
      - DEFAULT_WORKSPACE=/config
    volumes:
      - /mnt/app_config/homeassistant:/config
    ports:
      - 12321:8443
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/app_config/ha-matter-server:/data
      - /run/dbus:/run/dbus:ro
    security_opt:
      - apparmor=unconfined