#!/usr/bin/env bash

ls *.mkv | while read origFile ;
do
  echo "Writing $origFile";
  /usr/lib/jellyfin-ffmpeg/ffmpeg -fflags genpts -i "$origFile" -hide_banner -loglevel error -map 0:v -map 0:a -map 0:s -map_chapters 0 -c:v copy -c:a copy -c:s copy newFile.mkv < /dev/null ;
  mv newFile.mkv "$origFile" ;
done
echo "Done"