---
# LXC virtual users for container mapping

- name: create nas_shares group for lxc mapping
  ansible.builtin.group:
    name: "{{ nas_group }}"
    gid: "{{ nas_gid }}"
    state: present

- name: create nas user for lxc mapping
  ansible.builtin.user:
    name: "{{ nas_user }}"
    uid: "{{ nas_uid }}"
    group: "{{ nas_group }}"
    create_home: yes
    shell: /bin/bash
    state: present
