services:
  dockerstats:
    image: drakonis96/dockerstats:latest
    container_name: docker-stats
    environment:
      LOGIN_MODE: popup
      CADVISOR_URL: http://cadvisor:8080
      USERS_DB_PATH: /app/data/users.db
    ports:
      - "5001:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/app_config/dockerstats:/app/data
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    privileged: true
    command:
      - --docker_only=true
      - --housekeeping_interval=10s
