services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "8500:5000"
    volumes:
      - /mnt/app_config/registry/data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"