apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Prod
    server: https://acme-v02.api.letsencrypt.org/directory

    # Staging
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

    # A private key is created as part of the registration with ACME. You
    # don't need to create this, you just tell the Issuer what secret to 
    # store it in.
    privateKeySecretRef:
      name: letsencrypt

    solvers:
    # - selector:
    #     dnsZones:
    #       - "kye.dev"
    - selector: {}
      dns01:
        route53:
          region: us-west-2
          accessKeyID: AKIA5EIITELWDVIQOSJM

          # k8s secret that holds our AWS secret access key.
          secretAccessKeySecretRef:
            name: aws-cert-secret-key
            key: secret-access-key