#!/bin/bash
set -ex

_scripts="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export $(grep -v '^#' $_project/.env | xargs)

# kubectl create namespace traefik
# helm install -f k3os/traefik3.yaml --namespace=traefik traefik traefik/traefik
kubectl apply -f k3os/traefik.yaml
helm install --namespace=traefik traefik traefik/traefik

# delete
# helm uninstall --namespace=traefik traefik traefik/traefik

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.yaml

# delete
# kubectl delete -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.yaml

kubectl -n cert-manager create secret generic aws-cert-secret-key --from-literal=secret-access-key=$TRAEFIK_AWS_SECRET


# cert manager logs
# kubectl logs -n cert-manager deployment/cert-manager --tail=10 -f


# helm upgrade -n traefik \
#   traefik traefik/traefik \
#   -f k3os/traefik2.yaml